### ISSUE TITLE
Unhandled Promise

### ISSUE THREAD

**Issue by jacksonmelcher** [ringcentral/ringcentral-js#128]
When following [this](https://developers.ringcentral.com/guide/team-messaging/quick-start/node) tutorial I'm getting an Unhandled Promise error:
```
node:59834) UnhandledPromiseRejectionWarning: Error: Unauthorized for this grant type
    at Client.<anonymous> (/path/to/project/node_modules/@ringcentral/sdk/lib/http/Client.js:115:35)
    at step (/path/to/project/node_modules/@ringcentral/sdk/lib/http/Client.js:56:23)
    at Object.next (/path/to/project/node_modules/@ringcentral/sdk/lib/http/Client.js:37:53)
    at fulfilled (/path/to/project/node_modules/@ringcentral/sdk/lib/http/Client.js:28:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:59834) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59834) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It looks like the source of the error is the `Client.js` file within the SDK. 
Let me know how I can go about fixing this.

Thank you.

**Comment by tylerlong** [comment]
@jacksonmelcher  it is not a SDK issue.

"Unauthorized for this grant type" means your RingCentral app doesn't support password flow.

You can send email to devsupport@ringcentral.com if you need further help.
