### ISSUE TITLE
Unable to fax a file from file system.

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#15]
Please read this issue first: https://github.com/ringcentral/ringcentral-js/issues/13

The fax feature didn't work. Now it works but I still fail to fax a file from file system.

Sample code:

```javascript
var SDK = require('ringcentral');
var FormData = require('form-data');

var sdk = new SDK({
    appKey: 'xxx',
    appSecret: 'xxx',
    server: 'https://platform.ringcentral.com'
});

var formData = new FormData();

var body = {
    to: [{phoneNumber: '16508370092'}],
    faxResolution: 'High'
};

formData.append('json', new Buffer(JSON.stringify(body)), {filename: 'request.json', contentType: 'application/json'});

formData.append('attachment', new Buffer('some plain text'), {filename: 'text.txt', contentType: 'text/plain'});

formData.append('attachment', require('fs').createReadStream('/Users/tyler.liu/Desktop/test.pdf'));

console.log('sending fax...');

sdk.platform()
    .login({
        username: 'xxx',
        extension: null,
        password: 'xxx',
    })
    .then(function(response) {

        console.log('Login successful');

        return sdk.platform()
            .post('/account/~/extension/~/fax', formData)
            .then(function() {
                console.log('fax sent');
            });

    })
    .catch(function(e) {
        console.error(e.apiResponse.request());
        console.error(e.stack);
    });
```

The code above fails with the following error message:

```
sending fax...
Login successful
Body {
  method: 'POST',
  headers: 
   Headers {
     _headers: 
      { accept: [Object],
        'x-user-agent': [Object],
        'client-id': [Object],
        authorization: [Object] } },
  url: 'https://platform.ringcentral.com/restapi/v1.0/account/~/extension/~/fax',
  follow: 20,
  compress: true,
  counter: 0,
  agent: undefined,
  body: 
   FormData {
     _overheadLength: 477,
     _valueLength: 76,
     _lengthRetrievers: [ [Function] ],
     writable: false,
     readable: true,
     dataSize: 0,
     maxDataSize: 2097152,
     pauseStreams: true,
     _released: false,
     _streams: 
      [ '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="json"; filename="request.json"\r\nContent-Type: application/json\r\n\r\n',
        <Buffer 7b 22 74 6f 22 3a 5b 7b 22 70 68 6f 6e 65 4e 75 6d 62 65 72 22 3a 22 31 36 35 30 38 33 37 30 30 39 32 22 7d 5d 2c 22 66 61 78 52 65 73 6f 6c 75 74 69 ... >,
        [Function: bound ],
        '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="attachment"; filename="text.txt"\r\nContent-Type: text/plain\r\n\r\n',
        <Buffer 73 6f 6d 65 20 70 6c 61 69 6e 20 74 65 78 74>,
        [Function: bound ],
        '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="attachment"; filename="test.pdf"\r\nContent-Type: application/pdf\r\n\r\n',
        [Object],
        [Function: bound ] ],
     _currentStream: null,
     _boundary: '--------------------------471797134592888957481870',
     error: 
      { [Error: Cannot calculate proper length in synchronous way.]
        apiResponse: [Object],
        originalMessage: 'Cannot calculate proper length in synchronous way.' } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false,
  protocol: 'https:',
  hostname: 'platform.ringcentral.com',
  port: null,
  path: '/restapi/v1.0/account/~/extension/~/fax',
  auth: null,
  originalBody: 
   FormData {
     _overheadLength: 477,
     _valueLength: 76,
     _lengthRetrievers: [ [Function] ],
     writable: false,
     readable: true,
     dataSize: 0,
     maxDataSize: 2097152,
     pauseStreams: true,
     _released: false,
     _streams: 
      [ '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="json"; filename="request.json"\r\nContent-Type: application/json\r\n\r\n',
        <Buffer 7b 22 74 6f 22 3a 5b 7b 22 70 68 6f 6e 65 4e 75 6d 62 65 72 22 3a 22 31 36 35 30 38 33 37 30 30 39 32 22 7d 5d 2c 22 66 61 78 52 65 73 6f 6c 75 74 69 ... >,
        [Function: bound ],
        '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="attachment"; filename="text.txt"\r\nContent-Type: text/plain\r\n\r\n',
        <Buffer 73 6f 6d 65 20 70 6c 61 69 6e 20 74 65 78 74>,
        [Function: bound ],
        '----------------------------471797134592888957481870\r\nContent-Disposition: form-data; name="attachment"; filename="test.pdf"\r\nContent-Type: application/pdf\r\n\r\n',
        [Object],
        [Function: bound ] ],
     _currentStream: null,
     _boundary: '--------------------------471797134592888957481870',
     error: 
      { [Error: Cannot calculate proper length in synchronous way.]
        apiResponse: [Object],
        originalMessage: 'Cannot calculate proper length in synchronous way.' } } }
Error: Cannot calculate proper length in synchronous way.
    at FormData.getLengthSync (/Users/tyler.liu/src/js/rc-test/node_modules/form-data/lib/form_data.js:316:17)
    at /Users/tyler.liu/src/js/rc-test/node_modules/node-fetch/index.js:95:48
    at lib$es6$promise$$internal$$initializePromise (/Users/tyler.liu/src/js/rc-test/node_modules/es6-promise/dist/es6-promise.js:408:9)
    at new lib$es6$promise$promise$$Promise (/Users/tyler.liu/src/js/rc-test/node_modules/es6-promise/dist/es6-promise.js:581:60)
    at new Fetch (/Users/tyler.liu/src/js/rc-test/node_modules/node-fetch/index.js:48:9)
    at Fetch (/Users/tyler.liu/src/js/rc-test/node_modules/node-fetch/index.js:36:10)
    at Client._callee2$ (/Users/tyler.liu/src/js/rc-test/node_modules/ringcentral/build/ringcentral.js:1492:53)
    at tryCatch (/Users/tyler.liu/src/js/rc-test/node_modules/ringcentral/build/ringcentral.js:125:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/tyler.liu/src/js/rc-test/node_modules/ringcentral/build/ringcentral.js:393:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/tyler.liu/src/js/rc-test/node_modules/ringcentral/build/ringcentral.js:158:21)
```

There was no problem when I removed this line from source code: `formData.append('attachment', require('fs').createReadStream('/Users/tyler.liu/Desktop/test.pdf'));`  

From the error message, it seems that the code/library failed to calculate the file length.

Let me do more investigation and get back to this issue later.  By the way, C# SDK works without problem, let me compare the code.

**Comment by tylerlong** [comment]
I've found a solution / workaround:

Replace the following code:

```javascript
formData.append('attachment', require('fs').createReadStream('/Users/tyler.liu/Desktop/test.pdf'));
```

with

```javascript
formData.append('attachment', fs.createReadStream('/Users/tyler.liu/Desktop/test.pdf'),
  {filename: 'test.pdf', contentType: 'application/pdf', knownLength: fs.statSync('/Users/tyler.liu/Desktop/test.pdf')['size'] });
```

I think we should either update the library itself or update the readme documentation.

**Comment by kirill-konshin** [comment]
Yes, this is what you have to do in order to make `form-data` package to work with `node-fetch` and FS. You can also read a file vial `fs.readFileSync()` if you need to do it in a simple way.
