### ISSUE TITLE
Some issues about Subscription

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#195]
##  It doesn't work with latest version of PubNub

- `<script type="text/javascript" src="https://unpkg.com/pubnub@4.37.0/dist/web/pubnub.js"></script>` works
- `<script type="text/javascript" src="https://unpkg.com/pubnub@7.2.1/dist/web/pubnub.js"></script>` doesn't work

Error message is 

```
pubnub.js:679 Uncaught (in promise) Error: One of the following configuration options has to be provided: `uuid` or `userId`
    at new default_1 (pubnub.js:679:27)
    at default_1 (pubnub.js:7355:26)
    at new default_1 (pubnub.js:11715:28)
    at Subscription._subscribeAtPubNub (Subscription.ts:358:28)
    at Subscription.setSubscription (Subscription.ts:114:14)
    at Subscription.<anonymous> (Subscription.ts:174:18)
    at step (ringcentral-subscriptions.js:163:23)
    at Object.next (ringcentral-subscriptions.js:144:53)
    at fulfilled (ringcentral-subscriptions.js:135:58)
```

## README file has wrong link

https://github.com/ringcentral/ringcentral-js/tree/master/subscriptions#get-the-code

https://unpkg.com/browse/@ringcentral/subscriptions@latest/dist/ringcentral-subscriptions.js needs to be changed to https://unpkg.com/@ringcentral/subscriptions@latest/dist/ringcentral-subscriptions.js

**Comment by SushilMallRC** [comment]
As PubNub is deprecated from the SDK So marking close this issue, please feel free to reopen if it's required.
