### ISSUE TITLE
Uncaught subscription renew errors cause server app to crash

### ISSUE THREAD

**Issue by zengfenfei** [ringcentral/ringcentral-js#70]
Error logs:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Token not found
    at Client._callee$ (/home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:1574:35)
    at tryCatch (/home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:309:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:577:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:342:21)
    at step (/home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:1514:191)
    at /home/ubuntu/node-apps/xxx/node_modules/ringcentral/build/ringcentral.js:1514:368
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by zengfenfei** [comment]
Seems the issue with #52

**Comment by kirill-konshin** [comment]
On a server your own code or a framework that you use has to take care of uncaught exceptions and unhandled rejections and react appropriately.

In order to simplify this for subscriptions 2 new events were added in 4e76bafb98e7173290a7d4202f8c91109020add0. Will be released in 3.1.2.

**Comment by zengfenfei** [comment]
Of course, my own code should handle all uncaught exceptions. The situation here is, the error is thrown in the **setInterval**, so the app doesn't have the chance to catch the exception.

**Comment by kirill-konshin** [comment]
After the fix it has such chance. But even w/o a fix if you define a handler for unhandled rejection you can capture it.
